package(                                                                                            
  default_visibility = ["//:data_consumer"]                                                                   
) 

proto_library (
	name = "yahoo_quote_parser_config_proto",
	srcs = ["yahoo_quote_parser_config.proto"],                                                                   
)
                                                                                                    
cc_proto_library(                                                                                   
    name = "yahoo_quote_parser_config_cc_proto",                                                                  
    deps = [":yahoo_quote_parser_config_proto"],                                                                  
)                                                                                                   
