load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_binary(
    name = "eye",
    srcs = ["eye.py"],
)

py_binary(
  name = "status",
  srcs = ["status.py"],
)

py_binary(
  name = "tensor_example",
  srcs = ["tensor_example.py"],
)

py_binary(
  name = "gelu",
  srcs = ["gelu.py"],
)

py_binary(
  name = "train",
  srcs = ["train.py"],
)

py_binary(
  name = "mnist",
  srcs = ["mnist.py"],
)

py_binary(
  name = "structured",
  srcs = ["structured.py"],
)

