package (
		default_visibility = ["//:data_consumer"],
)

filegroup(
    name = "yahoo_quote_microsoft_html",
    srcs = ["yahoo_quote_microsoft.html"],
)

filegroup(
    name = "yahoo_quote_gspc_html",
    srcs = ["yahoo_quote_gspc.html"],
)
